apiVersion: v1
kind: Service
metadata:
  name: nginx-internal-service
spec:
  type: ClusterIP
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80 # The port the SERVICE listens on
      targetPort: 80 # The port the POD listens on